Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/routes/admin.py", line 20, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/routes/admin.py", line 243, in subscriptions
    return render_template(template,
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/runner/workspace/templates/admin/admin-mobile/subscriptions.html", line 617, in top-level template code
    <option value="{{ plan.id }}" {% if plan_id|int == plan.id %}selected{% endif %}>
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/jinja2/filters.py", line 957, in do_int
    return int(value)
           ^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'plan_id' is undefined
156.160.129.88,10.81.12.119,172.31.128.14 - - [22/May/2025 16:27:53] "GET /admin/subscriptions HTTP/1.1" 500 29806 0.056694
156.160.129.88,10.81.12.119,172.31.128.14 - - [22/May/2025 16:27:53] "GET /admin/subscriptions?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 192 0.000553
(5069) accepted ('172.31.128.14', 58850)
156.160.129.88,10.81.12.119,172.31.128.14 - - [22/May/2025 16:27:54] "GET /admin/subscriptions?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 195 0.000635
(5069) accepted ('172.31.128.14', 58852)
156.160.129.88,10.81.12.119,172.31.128.14 - - [22/May/2025 16:27:54] "GET /admin/subscriptions?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 195 0.000584
(5069) accepted ('172.31.128.14', 58858)
156.160.129.88,10.81.12.119,172.31.128.14 - - [22/May/2025 16:27:54] "GET /admin/subscriptions?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 195 0.000499
